version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=cuidar@123
      - MYSQL_DATABASE=cuidar
      - MYSQL_USER=cuidar
      - MYSQL_PASSWORD=cuidar@123
    volumes:
      - /data/mysql
    ports:
    - 3333:3306
    container_name: cuidar-db